apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
    - name: http-in
      port: 10000
      targetPort: 10000
    - name: admin
      port: 9901
      targetPort: 9901

