apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    app: rabbit
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: admin
      port: 15672
      targetPort: 15672
