apiVersion: v1
kind: Service
metadata:
  name: firstvoices
spec:
  selector:
    app: firstvoices
  ports:
    - name: http-in
      port: 8080
      targetPort: 8080
    - name: java-debug
      port: 8787
      targetPort: 8787
