export const PAGE_NAVIGATION = 'PAGE_NAVIGATION'

export const AUDIO_ERRORED = 'AUDIO_ERRORED'
export const AUDIO_UNLOADED = 'AUDIO_UNLOADED'
export const AUDIO_LOADING = 'AUDIO_LOADING'
export const AUDIO_LOADED = 'AUDIO_LOADED'
export const AUDIO_STOPPED = 'AUDIO_STOPPED'
export const AUDIO_PLAYING = 'AUDIO_PLAYING'
export const NATIVE_AUDIO_PLAYING = 'NATIVE_AUDIO_PLAYING'

export const WIDGET_HERO = 'WIDGET_HERO'
// HERO VARIANTS
export const WIDGET_HERO_SEARCH = 'WIDGET_HERO_SEARCH'
export const WIDGET_HERO_LEFT = 'WIDGET_HERO_LEFT'
export const WIDGET_HERO_CENTER = 'WIDGET_HERO_CENTER'

export const WIDGET_SCHEDULE = 'WIDGET_SCHEDULE'

export const WIDGET_LIST = 'WIDGET_LIST'
export const WIDGET_LIST_WORD = 'WIDGET_LIST_WORD'
export const WIDGET_LIST_PHRASE = 'WIDGET_LIST_PHRASE'
export const WIDGET_LIST_SONG = 'WIDGET_LIST_SONG'
export const WIDGET_LIST_STORY = 'WIDGET_LIST_STORY'
export const WIDGET_LIST_MIXED = 'WIDGET_LIST_MIXED'
export const WIDGET_LIST_GENERIC = 'WIDGET_LIST_GENERIC'

export const WIDGET_WELCOME = 'WIDGET_WELCOME'
export const WIDGET_ALPHABET = 'WIDGET_ALPHABET'
export const WIDGET_STATS = 'WIDGET_STATS'
export const WIDGET_GALLERY = 'WIDGET_GALLERY'
export const WIDGET_CONTACT = 'WIDGET_CONTACT'
