version: '3'
services:
  nuxeo-backend:
      environment:
        - NUXEO_ES_CLUSTER_NAME=firstvoices
        - NUXEO_ES_INDEX_NAME=nuxeo-fv
        - NUXEO_ES_REPLICAS=0
        - NUXEO_ES_HOSTS=elasticsearch:9300
        - NUXEO_TEMPLATES=postgresql
      depends_on:
      - elasticsearch
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.4'
    container_name: nuxeo-elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
      - '443:443'
    environment:
      - discovery.type=single-node
      - cluster.name=firstvoices
    labels:
      - "ca.firstvoices.group=local_docker"