export const queryParam = 'category'
export const filterListData = [
  {
    _baseOptions: {
      schemas: ['*'],
      enrichers: {},
      fetchProperties: {},
      translateProperties: {},
      headers: {
        'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
        properties: '*',
        'Nuxeo-Transaction-Timeout': 60000,
        Accept: 'application/json',
      },
      timeout: 30000,
      httpTimeout: 30000,
    },
    _nuxeo: {
      _baseOptions: {
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {},
        timeout: 60000,
        httpTimeout: 30000,
      },
      _baseURL: 'http://0.0.0.0:3001/nuxeo/',
      _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
      _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
      _auth: null,
      _authenticationRefreshedListeners: [],
      connected: false,
      _activeRequests: 0,
    },
    _repository: {
      _baseOptions: {
        repositoryName: 'default',
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {
          'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
          properties: '*',
          'Nuxeo-Transaction-Timeout': 60000,
          Accept: 'application/json',
        },
        timeout: 30000,
        httpTimeout: 30000,
      },
      _nuxeo: {
        _baseOptions: {
          schemas: ['*'],
          enrichers: {},
          fetchProperties: {},
          translateProperties: {},
          headers: {},
          timeout: 60000,
          httpTimeout: 30000,
        },
        _baseURL: 'http://0.0.0.0:3001/nuxeo/',
        _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
        _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
        _auth: null,
        _authenticationRefreshedListeners: [],
        connected: false,
        _activeRequests: 0,
      },
    },
    properties: {
      'uid:uid': null,
      'uid:major_version': 0,
      'uid:minor_version': 0,
      'file:content': null,
      'common:icon-expanded': null,
      'common:icon': null,
      'fva:language': 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
      'fva:dialect': '94efa9c6-033d-4acc-88a6-4813bd6815d9',
      'fva:family': '301a0f9c-6757-4038-a2ab-c34b60157edd',
      'dc:description': null,
      'dc:language': null,
      'dc:coverage': null,
      'dc:valid': null,
      'dc:creator': 'Administrator',
      'dc:modified': '2020-11-06T17:55:26.841Z',
      'dc:lastContributor': 'Administrator',
      'dc:rights': null,
      'dc:expired': null,
      'dc:format': null,
      'dc:created': '2020-11-06T17:55:26.841Z',
      'dc:title': 'Parent Category II',
      'dc:issued': null,
      'dc:nature': null,
      'dc:subjects': [],
      'dc:contributors': ['Administrator'],
      'dc:source': null,
      'dc:publisher': null,
      'fvl:import_id': null,
      'fvl:created_date': null,
      'fvl:assigned_usr_id': null,
      'fvl:import_id-v2': null,
      'fvl:change_date': null,
      'fvl:status_id': null,
      'fvcategory:image': null,
    },
    _dirtyProperties: {},
    'entity-type': 'document',
    repository: 'default',
    uid: '2100b13d-218e-4660-927a-9f80475a8019',
    path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category II',
    type: 'FVCategory',
    state: 'New',
    parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
    isCheckedOut: true,
    isVersion: false,
    isProxy: false,
    changeToken: '1-0',
    isTrashed: false,
    title: 'Parent Category II',
    lastModified: '2020-11-06T17:55:26.841Z',
    facets: ['Folderish', 'Publishable'],
    contextParameters: {
      ancestry: {
        family: { uid: '301a0f9c-6757-4038-a2ab-c34b60157edd', 'dc:title': 'Test' },
        language: { uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b', 'dc:title': 'Test' },
        dialect: {
          uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
          'dc:title': 'iooᑎẄij',
          path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
          'fvdialect:country': null,
          'fvdialect:region': null,
        },
      },
      breadcrumb: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '12029099-67fb-488b-a0a6-cac829a716bf',
            path: '/FV',
            type: 'Domain',
            state: 'project',
            parentRef: '3a351047-cb96-4184-972f-6a5ad7a2ad2d',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'FV',
            lastModified: '2020-11-06T00:35:39.480Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '186c5634-917b-44bf-8aab-07b2290138e7',
            path: '/FV/Workspaces',
            type: 'WorkspaceRoot',
            state: 'project',
            parentRef: '12029099-67fb-488b-a0a6-cac829a716bf',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Workspaces',
            lastModified: '2020-11-06T00:35:39.485Z',
            facets: ['Folderish', 'SuperSpace', 'HiddenInCreation', 'NotCollectionMember'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            path: '/FV/Workspaces/Data',
            type: 'Workspace',
            state: 'project',
            parentRef: '186c5634-917b-44bf-8aab-07b2290138e7',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '23-0',
            isTrashed: false,
            title: 'Data',
            lastModified: '2020-11-16T21:27:38.643Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            path: '/FV/Workspaces/Data/Test',
            type: 'FVLanguageFamily',
            state: 'New',
            parentRef: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.529Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            path: '/FV/Workspaces/Data/Test/Test',
            type: 'FVLanguage',
            state: 'New',
            parentRef: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.551Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
            type: 'FVDialect',
            state: 'Published',
            parentRef: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '11-0',
            isTrashed: false,
            title: 'iooᑎẄij',
            lastModified: '2020-11-06T17:58:46.395Z',
            facets: ['Versionable', 'Folderish', 'Publishable', 'Commentable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories',
            type: 'FVCategories',
            state: 'Published',
            parentRef: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '4-0',
            isTrashed: false,
            title: 'Categories',
            lastModified: '2020-11-06T17:58:46.473Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '2100b13d-218e-4660-927a-9f80475a8019',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category II',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Parent Category II',
            lastModified: '2020-11-06T17:55:26.841Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      children: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '2e6a992f-2023-4be9-8317-2e7a824a349b',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category II/Child Category IIII',
            type: 'FVCategory',
            state: 'New',
            parentRef: '2100b13d-218e-4660-927a-9f80475a8019',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category IIII',
            lastModified: '2020-11-06T17:55:26.847Z',
            facets: ['Folderish', 'Publishable'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '727cbb38-913f-40d9-9bde-ad83bf4129c9',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category II/Child Category IIᑕ',
            type: 'FVCategory',
            state: 'New',
            parentRef: '2100b13d-218e-4660-927a-9f80475a8019',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category IIᑕ',
            lastModified: '2020-11-06T17:55:26.854Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      parentDoc: { id: 'd843c44c-2b3c-46bb-809d-73c5629cd817', title: 'Categories', type: 'FVCategories' },
    },
  },
  {
    _baseOptions: {
      schemas: ['*'],
      enrichers: {},
      fetchProperties: {},
      translateProperties: {},
      headers: {
        'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
        properties: '*',
        'Nuxeo-Transaction-Timeout': 60000,
        Accept: 'application/json',
      },
      timeout: 30000,
      httpTimeout: 30000,
    },
    _nuxeo: {
      _baseOptions: {
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {},
        timeout: 60000,
        httpTimeout: 30000,
      },
      _baseURL: 'http://0.0.0.0:3001/nuxeo/',
      _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
      _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
      _auth: null,
      _authenticationRefreshedListeners: [],
      connected: false,
      _activeRequests: 0,
    },
    _repository: {
      _baseOptions: {
        repositoryName: 'default',
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {
          'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
          properties: '*',
          'Nuxeo-Transaction-Timeout': 60000,
          Accept: 'application/json',
        },
        timeout: 30000,
        httpTimeout: 30000,
      },
      _nuxeo: {
        _baseOptions: {
          schemas: ['*'],
          enrichers: {},
          fetchProperties: {},
          translateProperties: {},
          headers: {},
          timeout: 60000,
          httpTimeout: 30000,
        },
        _baseURL: 'http://0.0.0.0:3001/nuxeo/',
        _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
        _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
        _auth: null,
        _authenticationRefreshedListeners: [],
        connected: false,
        _activeRequests: 0,
      },
    },
    properties: {
      'uid:uid': null,
      'uid:major_version': 0,
      'uid:minor_version': 0,
      'file:content': null,
      'common:icon-expanded': null,
      'common:icon': null,
      'fva:language': 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
      'fva:dialect': '94efa9c6-033d-4acc-88a6-4813bd6815d9',
      'fva:family': '301a0f9c-6757-4038-a2ab-c34b60157edd',
      'dc:description': null,
      'dc:language': null,
      'dc:coverage': null,
      'dc:valid': null,
      'dc:creator': 'Administrator',
      'dc:modified': '2020-11-06T17:55:26.892Z',
      'dc:lastContributor': 'Administrator',
      'dc:rights': null,
      'dc:expired': null,
      'dc:format': null,
      'dc:created': '2020-11-06T17:55:26.892Z',
      'dc:title': 'Parent Category O',
      'dc:issued': null,
      'dc:nature': null,
      'dc:subjects': [],
      'dc:contributors': ['Administrator'],
      'dc:source': null,
      'dc:publisher': null,
      'fvl:import_id': null,
      'fvl:created_date': null,
      'fvl:assigned_usr_id': null,
      'fvl:import_id-v2': null,
      'fvl:change_date': null,
      'fvl:status_id': null,
      'fvcategory:image': null,
    },
    _dirtyProperties: {},
    'entity-type': 'document',
    repository: 'default',
    uid: 'b64f12e3-3f83-4046-99d5-872ff16e0762',
    path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category O',
    type: 'FVCategory',
    state: 'New',
    parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
    isCheckedOut: true,
    isVersion: false,
    isProxy: false,
    changeToken: '1-0',
    isTrashed: false,
    title: 'Parent Category O',
    lastModified: '2020-11-06T17:55:26.892Z',
    facets: ['Folderish', 'Publishable'],
    contextParameters: {
      ancestry: {
        family: { uid: '301a0f9c-6757-4038-a2ab-c34b60157edd', 'dc:title': 'Test' },
        language: { uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b', 'dc:title': 'Test' },
        dialect: {
          uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
          'dc:title': 'iooᑎẄij',
          path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
          'fvdialect:country': null,
          'fvdialect:region': null,
        },
      },
      breadcrumb: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '12029099-67fb-488b-a0a6-cac829a716bf',
            path: '/FV',
            type: 'Domain',
            state: 'project',
            parentRef: '3a351047-cb96-4184-972f-6a5ad7a2ad2d',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'FV',
            lastModified: '2020-11-06T00:35:39.480Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '186c5634-917b-44bf-8aab-07b2290138e7',
            path: '/FV/Workspaces',
            type: 'WorkspaceRoot',
            state: 'project',
            parentRef: '12029099-67fb-488b-a0a6-cac829a716bf',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Workspaces',
            lastModified: '2020-11-06T00:35:39.485Z',
            facets: ['Folderish', 'SuperSpace', 'HiddenInCreation', 'NotCollectionMember'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            path: '/FV/Workspaces/Data',
            type: 'Workspace',
            state: 'project',
            parentRef: '186c5634-917b-44bf-8aab-07b2290138e7',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '23-0',
            isTrashed: false,
            title: 'Data',
            lastModified: '2020-11-16T21:27:38.643Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            path: '/FV/Workspaces/Data/Test',
            type: 'FVLanguageFamily',
            state: 'New',
            parentRef: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.529Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            path: '/FV/Workspaces/Data/Test/Test',
            type: 'FVLanguage',
            state: 'New',
            parentRef: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.551Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
            type: 'FVDialect',
            state: 'Published',
            parentRef: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '11-0',
            isTrashed: false,
            title: 'iooᑎẄij',
            lastModified: '2020-11-06T17:58:46.395Z',
            facets: ['Versionable', 'Folderish', 'Publishable', 'Commentable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories',
            type: 'FVCategories',
            state: 'Published',
            parentRef: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '4-0',
            isTrashed: false,
            title: 'Categories',
            lastModified: '2020-11-06T17:58:46.473Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'b64f12e3-3f83-4046-99d5-872ff16e0762',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category O',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Parent Category O',
            lastModified: '2020-11-06T17:55:26.892Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      children: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '2446869b-8109-42ff-89a6-b37b4ddb35c8',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category O/Child Category OII',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'b64f12e3-3f83-4046-99d5-872ff16e0762',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category OII',
            lastModified: '2020-11-06T17:55:26.902Z',
            facets: ['Folderish', 'Publishable'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '15bb8a84-f203-4a64-aa37-b97787d8b1ca',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category O/Child Category Oᑕ',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'b64f12e3-3f83-4046-99d5-872ff16e0762',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category Oᑕ',
            lastModified: '2020-11-06T17:55:26.908Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      parentDoc: { id: 'd843c44c-2b3c-46bb-809d-73c5629cd817', title: 'Categories', type: 'FVCategories' },
    },
  },
  {
    _baseOptions: {
      schemas: ['*'],
      enrichers: {},
      fetchProperties: {},
      translateProperties: {},
      headers: {
        'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
        properties: '*',
        'Nuxeo-Transaction-Timeout': 60000,
        Accept: 'application/json',
      },
      timeout: 30000,
      httpTimeout: 30000,
    },
    _nuxeo: {
      _baseOptions: {
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {},
        timeout: 60000,
        httpTimeout: 30000,
      },
      _baseURL: 'http://0.0.0.0:3001/nuxeo/',
      _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
      _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
      _auth: null,
      _authenticationRefreshedListeners: [],
      connected: false,
      _activeRequests: 0,
    },
    _repository: {
      _baseOptions: {
        repositoryName: 'default',
        schemas: ['*'],
        enrichers: {},
        fetchProperties: {},
        translateProperties: {},
        headers: {
          'enrichers.document': 'ancestry, parentDoc, breadcrumb, children',
          properties: '*',
          'Nuxeo-Transaction-Timeout': 60000,
          Accept: 'application/json',
        },
        timeout: 30000,
        httpTimeout: 30000,
      },
      _nuxeo: {
        _baseOptions: {
          schemas: ['*'],
          enrichers: {},
          fetchProperties: {},
          translateProperties: {},
          headers: {},
          timeout: 60000,
          httpTimeout: 30000,
        },
        _baseURL: 'http://0.0.0.0:3001/nuxeo/',
        _restURL: 'http://0.0.0.0:3001/nuxeo/api/v1/',
        _automationURL: 'http://0.0.0.0:3001/nuxeo/api/v1/automation/',
        _auth: null,
        _authenticationRefreshedListeners: [],
        connected: false,
        _activeRequests: 0,
      },
    },
    properties: {
      'uid:uid': null,
      'uid:major_version': 0,
      'uid:minor_version': 0,
      'file:content': null,
      'common:icon-expanded': null,
      'common:icon': null,
      'fva:language': 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
      'fva:dialect': '94efa9c6-033d-4acc-88a6-4813bd6815d9',
      'fva:family': '301a0f9c-6757-4038-a2ab-c34b60157edd',
      'dc:description': null,
      'dc:language': null,
      'dc:coverage': null,
      'dc:valid': null,
      'dc:creator': 'Administrator',
      'dc:modified': '2020-11-06T17:55:26.859Z',
      'dc:lastContributor': 'Administrator',
      'dc:rights': null,
      'dc:expired': null,
      'dc:format': null,
      'dc:created': '2020-11-06T17:55:26.859Z',
      'dc:title': 'Parent Category ᑕ',
      'dc:issued': null,
      'dc:nature': null,
      'dc:subjects': [],
      'dc:contributors': ['Administrator'],
      'dc:source': null,
      'dc:publisher': null,
      'fvl:import_id': null,
      'fvl:created_date': null,
      'fvl:assigned_usr_id': null,
      'fvl:import_id-v2': null,
      'fvl:change_date': null,
      'fvl:status_id': null,
      'fvcategory:image': null,
    },
    _dirtyProperties: {},
    'entity-type': 'document',
    repository: 'default',
    uid: 'db456452-da58-4c75-81ba-8c5d13153c4e',
    path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category ᑕ',
    type: 'FVCategory',
    state: 'New',
    parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
    isCheckedOut: true,
    isVersion: false,
    isProxy: false,
    changeToken: '1-0',
    isTrashed: false,
    title: 'Parent Category ᑕ',
    lastModified: '2020-11-06T17:55:26.859Z',
    facets: ['Folderish', 'Publishable'],
    contextParameters: {
      ancestry: {
        family: { uid: '301a0f9c-6757-4038-a2ab-c34b60157edd', 'dc:title': 'Test' },
        language: { uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b', 'dc:title': 'Test' },
        dialect: {
          uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
          'dc:title': 'iooᑎẄij',
          path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
          'fvdialect:country': null,
          'fvdialect:region': null,
        },
      },
      breadcrumb: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '12029099-67fb-488b-a0a6-cac829a716bf',
            path: '/FV',
            type: 'Domain',
            state: 'project',
            parentRef: '3a351047-cb96-4184-972f-6a5ad7a2ad2d',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'FV',
            lastModified: '2020-11-06T00:35:39.480Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '186c5634-917b-44bf-8aab-07b2290138e7',
            path: '/FV/Workspaces',
            type: 'WorkspaceRoot',
            state: 'project',
            parentRef: '12029099-67fb-488b-a0a6-cac829a716bf',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Workspaces',
            lastModified: '2020-11-06T00:35:39.485Z',
            facets: ['Folderish', 'SuperSpace', 'HiddenInCreation', 'NotCollectionMember'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            path: '/FV/Workspaces/Data',
            type: 'Workspace',
            state: 'project',
            parentRef: '186c5634-917b-44bf-8aab-07b2290138e7',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '23-0',
            isTrashed: false,
            title: 'Data',
            lastModified: '2020-11-16T21:27:38.643Z',
            facets: ['Folderish', 'SuperSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            path: '/FV/Workspaces/Data/Test',
            type: 'FVLanguageFamily',
            state: 'New',
            parentRef: 'b413c052-618b-467b-8286-4cc1c3d8a209',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.529Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            path: '/FV/Workspaces/Data/Test/Test',
            type: 'FVLanguage',
            state: 'New',
            parentRef: '301a0f9c-6757-4038-a2ab-c34b60157edd',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '5-0',
            isTrashed: false,
            title: 'Test',
            lastModified: '2020-11-06T00:56:04.551Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij',
            type: 'FVDialect',
            state: 'Published',
            parentRef: 'c3f9c15b-2b28-4f9e-a4ed-cd2cf7cc5a9b',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '11-0',
            isTrashed: false,
            title: 'iooᑎẄij',
            lastModified: '2020-11-06T17:58:46.395Z',
            facets: ['Versionable', 'Folderish', 'Publishable', 'Commentable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories',
            type: 'FVCategories',
            state: 'Published',
            parentRef: '94efa9c6-033d-4acc-88a6-4813bd6815d9',
            isCheckedOut: false,
            isVersion: false,
            isProxy: false,
            changeToken: '4-0',
            isTrashed: false,
            title: 'Categories',
            lastModified: '2020-11-06T17:58:46.473Z',
            facets: ['Folderish', 'Publishable', 'PublishSpace'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'db456452-da58-4c75-81ba-8c5d13153c4e',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category ᑕ',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'd843c44c-2b3c-46bb-809d-73c5629cd817',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Parent Category ᑕ',
            lastModified: '2020-11-06T17:55:26.859Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      children: {
        'entity-type': 'documents',
        entries: [
          {
            'entity-type': 'document',
            repository: 'default',
            uid: 'c2d3c4c2-b35c-438e-ae87-872fefe274ab',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category ᑕ/Child Category ᑕII',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'db456452-da58-4c75-81ba-8c5d13153c4e',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category ᑕII',
            lastModified: '2020-11-06T17:55:26.871Z',
            facets: ['Folderish', 'Publishable'],
          },
          {
            'entity-type': 'document',
            repository: 'default',
            uid: '9c5c2e23-25df-4faa-bdb6-b297ba105461',
            path: '/FV/Workspaces/Data/Test/Test/iooᑎẄij/Categories/Parent Category ᑕ/Child Category ᑕᑕ',
            type: 'FVCategory',
            state: 'New',
            parentRef: 'db456452-da58-4c75-81ba-8c5d13153c4e',
            isCheckedOut: true,
            isVersion: false,
            isProxy: false,
            changeToken: '1-0',
            isTrashed: false,
            title: 'Child Category ᑕᑕ',
            lastModified: '2020-11-06T17:55:26.886Z',
            facets: ['Folderish', 'Publishable'],
          },
        ],
      },
      parentDoc: { id: 'd843c44c-2b3c-46bb-809d-73c5629cd817', title: 'Categories', type: 'FVCategories' },
    },
  },
]
