import DashboardDetailSidebarItemPresentation from 'components/DashboardDetail/DashboardDetailSidebarItem/DashboardDetailSidebarItemPresentation'
export default {
  Presentation: DashboardDetailSidebarItemPresentation,
}
