FROM python:3.9-alpine
EXPOSE 8080

RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev 


COPY requirements.txt .
RUN pip3 install -r requirements.txt --no-cache-dir
RUN apk --purge del .build-deps

COPY . .
WORKDIR fv
