const GET_TOKEN_STARTED = 'GET_TOKEN_STARTED';
const GET_TOKEN_COMPLETE = 'GET_TOKEN_COMPLETE';
const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';
const GET_TOKEN_NOT_LOGGED_IN = 'GET_TOKEN_NOT_LOGGED_IN';
const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
const GET_TOKEN_REQUEST_REFRESH = 'GET_TOKEN_REQUEST_REFRESH';

export {
  GET_TOKEN_COMPLETE,
  GET_TOKEN_ERROR,
  GET_TOKEN_NOT_LOGGED_IN,
  GET_TOKEN_STARTED,
  GET_TOKEN_REQUEST,
  GET_TOKEN_REQUEST_REFRESH
}

