export const DIRECTORY_FETCH_START = 'DIRECTORY_FETCH_START'
export const DIRECTORY_FETCH_SUCCESS = 'DIRECTORY_FETCH_SUCCESS'
export const DIRECTORY_FETCH_ERROR = 'DIRECTORY_FETCH_ERROR'
export const LABEL_DIRECTORY_FETCH_START = 'LABEL_DIRECTORY_FETCH_START'
export const LABEL_DIRECTORY_FETCH_SUCCESS = 'LABEL_DIRECTORY_FETCH_SUCCESS'
export const LABEL_DIRECTORY_FETCH_ERROR = 'LABEL_DIRECTORY_FETCH_ERROR'

